/**
 * SessionReviewModal - Unified dialog for session review and summarization
 *
 * Features:
 * - Backend selection + generation
 * - View/edit review content with markdown preview/edit toggle
 * - Browse past reviews for this session
 *
 * Layout:
 * +----------------------------------+
 * | Session Review              [X]  |
 * +--------+-------------------------+
 * | Left   | Main Content            |
 * | Side   | Title: [___________]    |
 * | bar    |                         |
 * |        | Summary  [Preview][Edit]|
 * | Backend| +---------------------+ |
 * | [v]    | | ## Summary          | |
 * | [Gen]  | | Work done here...   | |
 * |        | +---------------------+ |
 * | Past:  |                         |
 * | - Feb  | Generated by: claude    |
 * | - Jan  |                         |
 * +--------+-------------------------+
 * |           [Cancel] [Approve]     |
 * +----------------------------------+
 */

import React, { useState, useEffect, useCallback, memo } from 'react';
import { Modal, ModalFooter } from '../Modal/Modal';
import ReactMarkdown from 'react-markdown';
import './SessionReviewModal.css';

// Custom comparison function for memo - prevents re-renders when modal is open
// When modal is open, internal state manages the form, so we only need to re-render
// when isOpen changes from true to false (closing) or false to true (opening)
// Exception: we allow re-renders when currentReview or isGenerating changes (for streaming updates)
function arePropsEqual(prevProps: SessionReviewModalProps, nextProps: SessionReviewModalProps): boolean {
  // If modal is open in both prev and next
  if (prevProps.isOpen && nextProps.isOpen) {
    // Allow re-renders for streaming updates
    if (prevProps.currentReview !== nextProps.currentReview ||
        prevProps.isGenerating !== nextProps.isGenerating) {
      return false;
    }
    // Otherwise skip re-render - internal state handles the form
    return true;
  }
  // Otherwise use default shallow comparison for memo
  return false;
}

// Types for the review data
export interface SessionReview {
  summary_id: string;
  proposed_title: string;
  approved_title: string;
  markdown_content: string;
  work_done: string;
  files_modified: string[];
  decisions_made: string[];
  next_steps: string[];
  questions_raised: string[];
  turn_count_at_review: number;
  reviewed_at: string;
  reviewed_by_backend: string;
  status: 'pending' | 'approved' | 'rejected';
}

// Props for backend info
export interface BackendInfo {
  name: string;
  displayName: string;
}

// Props for the modal
export interface SessionReviewModalProps {
  isOpen: boolean;
  onClose: () => void;
  sessionId: string;
  sessionTitle: string;
  availableBackends: BackendInfo[];
  defaultBackend?: string;
  existingReviews: SessionReview[];
  onStartReview: (sessionId: string, backendName: string) => Promise<string>; // returns helper_id
  onApprove: (sessionId: string, summaryId: string, approvedTitle: string, editedMarkdown: string | null) => Promise<void>;
  // Current review being generated (streamed in)
  currentReview?: SessionReview | null;
  isGenerating?: boolean;
}

// Format date for display
function formatDate(isoString: string): string {
  if (!isoString) return '';
  const date = new Date(isoString);
  if (isNaN(date.getTime())) return isoString;
  return date.toLocaleDateString(undefined, {
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

// Convert structured review to markdown for editing
function formatReviewAsMarkdown(review: SessionReview): string {
  const sections: string[] = [];

  if (review.work_done) {
    sections.push(`## Summary\n\n${review.work_done}`);
  }

  if (review.files_modified.length > 0) {
    const items = review.files_modified.map(f => `- ${f}`).join('\n');
    sections.push(`## Files Modified\n\n${items}`);
  }

  if (review.decisions_made.length > 0) {
    const items = review.decisions_made.map(d => `- ${d}`).join('\n');
    sections.push(`## Decisions Made\n\n${items}`);
  }

  if (review.next_steps.length > 0) {
    const items = review.next_steps.map(n => `- ${n}`).join('\n');
    sections.push(`## Next Steps\n\n${items}`);
  }

  if (review.questions_raised.length > 0) {
    const items = review.questions_raised.map(q => `- ${q}`).join('\n');
    sections.push(`## Open Questions\n\n${items}`);
  }

  return sections.join('\n\n');
}

/**
 * SessionReviewModal - Main modal component
 */
export const SessionReviewModal = memo(function SessionReviewModal({
  isOpen,
  onClose,
  sessionId,
  sessionTitle,
  availableBackends,
  defaultBackend,
  existingReviews,
  onStartReview,
  onApprove,
  currentReview,
  isGenerating = false,
}: SessionReviewModalProps) {
  // State
  const [selectedBackend, setSelectedBackend] = useState(defaultBackend || '');
  const [review, setReview] = useState<SessionReview | null>(null);
  const [editedTitle, setEditedTitle] = useState('');
  const [editedMarkdown, setEditedMarkdown] = useState('');
  const [isEditMode, setIsEditMode] = useState(false);
  const [viewingHistoryIndex, setViewingHistoryIndex] = useState<number | null>(null);

  // Reset when modal opens
  useEffect(() => {
    if (isOpen) {
      setSelectedBackend(defaultBackend || availableBackends[0]?.name || '');
      setReview(null);
      setEditedTitle('');
      setEditedMarkdown('');
      setIsEditMode(false);
      setViewingHistoryIndex(null);
    }
  }, [isOpen, defaultBackend, availableBackends]);

  // Update from currentReview (streamed in from parent)
  useEffect(() => {
    if (currentReview) {
      setReview(currentReview);
      setEditedTitle(currentReview.proposed_title);
      setEditedMarkdown(currentReview.markdown_content || formatReviewAsMarkdown(currentReview));
      setViewingHistoryIndex(null);
    }
  }, [currentReview]);

  // Generate new review with selected backend
  const handleGenerate = useCallback(async () => {
    if (!selectedBackend) return;
    setViewingHistoryIndex(null);
    await onStartReview(sessionId, selectedBackend);
  }, [sessionId, selectedBackend, onStartReview]);

  // Load a past review from history
  const handleSelectHistory = useCallback((index: number) => {
    const pastReview = existingReviews[index];
    if (pastReview) {
      setViewingHistoryIndex(index);
      setReview(pastReview);
      setEditedTitle(pastReview.approved_title || pastReview.proposed_title);
      setEditedMarkdown(pastReview.markdown_content || formatReviewAsMarkdown(pastReview));
      setIsEditMode(false);
    }
  }, [existingReviews]);

  // Approve and save
  const handleApprove = useCallback(async () => {
    if (!review) return;
    const editedContent = isEditMode ? editedMarkdown : null;
    await onApprove(sessionId, review.summary_id, editedTitle, editedContent);
    onClose();
  }, [review, sessionId, editedTitle, isEditMode, editedMarkdown, onApprove, onClose]);

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Session Review"
      size="large"
      className="session-review-modal"
    >
      <div className="session-review-modal__layout">
        {/* Sidebar: Backend selection + History */}
        <aside className="session-review-modal__sidebar">
          {/* Backend selector */}
          <div className="sidebar-section">
            <label className="sidebar-label">Generate with</label>
            <select
              value={selectedBackend}
              onChange={e => setSelectedBackend(e.target.value)}
              disabled={isGenerating}
              className="backend-select"
            >
              {availableBackends.map(b => (
                <option key={b.name} value={b.name}>{b.displayName}</option>
              ))}
            </select>
            <button
              onClick={handleGenerate}
              disabled={isGenerating || !selectedBackend}
              className="btn btn-primary generate-btn"
            >
              {isGenerating ? 'Generating...' : 'Generate'}
            </button>
          </div>

          {/* Past reviews */}
          {existingReviews.length > 0 && (
            <div className="sidebar-section">
              <label className="sidebar-label">Past Reviews</label>
              <ul className="history-list">
                {existingReviews.map((r, i) => (
                  <li
                    key={r.summary_id}
                    className={`history-item ${viewingHistoryIndex === i ? 'active' : ''}`}
                    onClick={() => handleSelectHistory(i)}
                  >
                    <span className="history-date">{formatDate(r.reviewed_at)}</span>
                    <span className="history-backend">{r.reviewed_by_backend}</span>
                    {r.status === 'approved' && <span className="history-badge">&#x2713;</span>}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </aside>

        {/* Main content */}
        <main className="session-review-modal__main">
          {isGenerating ? (
            <div className="loading-state">
              <div className="loading-spinner" />
              <p>Generating review with {selectedBackend}...</p>
            </div>
          ) : review ? (
            <div className="review-content">
              {/* Title field */}
              <div className="title-field">
                <label>Session Title</label>
                <input
                  type="text"
                  value={editedTitle}
                  onChange={e => setEditedTitle(e.target.value)}
                  className="title-input"
                  placeholder="Enter session title..."
                />
              </div>

              {/* Summary with Preview/Edit toggle */}
              <div className="summary-field">
                <div className="summary-header">
                  <label>Summary</label>
                  <div className="mode-toggle">
                    <button
                      type="button"
                      className={`toggle-btn ${!isEditMode ? 'active' : ''}`}
                      onClick={() => setIsEditMode(false)}
                    >
                      Preview
                    </button>
                    <button
                      type="button"
                      className={`toggle-btn ${isEditMode ? 'active' : ''}`}
                      onClick={() => setIsEditMode(true)}
                    >
                      Edit
                    </button>
                  </div>
                </div>

                <div className="summary-body">
                  {isEditMode ? (
                    <textarea
                      value={editedMarkdown}
                      onChange={e => setEditedMarkdown(e.target.value)}
                      className="summary-editor"
                      spellCheck={false}
                      placeholder="# Summary&#10;&#10;Describe what was accomplished..."
                    />
                  ) : (
                    <div className="summary-preview">
                      <ReactMarkdown>{editedMarkdown}</ReactMarkdown>
                    </div>
                  )}
                </div>
              </div>

              {/* Metadata footer */}
              <div className="review-meta">
                <span>Generated by {review.reviewed_by_backend}</span>
                <span className="meta-separator">&#8226;</span>
                <span>At turn {review.turn_count_at_review}</span>
                {viewingHistoryIndex !== null && (
                  <>
                    <span className="meta-separator">&#8226;</span>
                    <span className="viewing-past">Viewing past review</span>
                  </>
                )}
              </div>
            </div>
          ) : (
            <div className="empty-state">
              <p>Select a backend and click <strong>Generate</strong> to review this session.</p>
              {existingReviews.length > 0 && (
                <p className="hint">Or select a past review from the sidebar.</p>
              )}
            </div>
          )}
        </main>
      </div>

      <ModalFooter>
        <button type="button" onClick={onClose} className="btn">Cancel</button>
        <button
          type="button"
          onClick={handleApprove}
          className="btn btn-primary"
          disabled={!review || !editedTitle.trim() || isGenerating}
        >
          Approve &amp; Save
        </button>
      </ModalFooter>
    </Modal>
  );
}, arePropsEqual);

export default SessionReviewModal;
