from dataclasses import dataclass, field
from typing import Optional, Any, Union
from datetime import datetime
from enum import Enum


class ContextMode(Enum):
    """How a turn should be included in context when forking.

    COPY: Include turn verbatim in fork
    COMPRESS: LLM summarizes the turn before fork starts
    DROP: Exclude from fork context
    """
    COPY = "copy"
    COMPRESS = "compress"  # New name - LLM compresses before fork
    SUMMARIZE = "summarize"  # Legacy alias for COMPRESS
    DROP = "drop"


@dataclass
class TextBlock:
    """Plain text content."""
    type: str = "text"
    text: str = ""


@dataclass
class ToolUseBlock:
    """Tool invocation by the assistant."""
    type: str = "tool_use"
    id: str = ""
    name: str = ""
    input: dict = field(default_factory=dict)


@dataclass
class ToolResultBlock:
    """Result from a tool invocation."""
    type: str = "tool_result"
    tool_use_id: str = ""
    content: str = ""
    is_error: bool = False


@dataclass
class InterruptionBlock:
    """Marker indicating the response was interrupted by the user."""
    type: str = "interruption"
    reason: str = "user_cancelled"  # e.g., "user_cancelled", "timeout"


@dataclass
class ErrorBlock:
    """Marker indicating the response ended with an error (truncated, decode error, etc.)."""
    type: str = "error"
    reason: str = "stream_error"  # e.g., "truncated", "json_decode_error"
    partial_tool_name: str = ""  # Tool name if a tool call was in progress
    partial_tool_input: str = ""  # Partial JSON if tool input was being streamed
    details: str = ""  # Error message or other details
    dump_file: str = ""  # Path to dumped content file for LLM completion


@dataclass
class LinkBlock:
    """Marker indicating a bidirectional link to another session."""
    type: str = "link"
    link_id: str = ""  # UUID for this link pair (same in both sessions)
    linked_session_id: str = ""  # The other session's ID
    summary: str = ""  # LLM-generated summary
    is_orphaned: bool = False  # True if linked session was deleted


@dataclass
class ForkBlock:
    """Marker indicating where a fork was created.

    Stored as a turn in the parent session's history. When nested forks exist,
    these blocks persist through merges, preserving the full fork history.
    """
    type: str = "fork"
    fork_id: str = ""  # UUID for this fork (same as child session ID typically)
    child_session_id: str = ""  # The forked session's ID
    fork_name: str = ""  # User-friendly name for the fork
    prompt: str = ""  # The prompt that started the fork
    status: str = "active"  # "active", "merged", "abandoned"


@dataclass
class MergeBlock:
    """Marker indicating where a fork was merged back.

    Stored as a turn in the parent session's history. Contains the merge summary,
    allowing nested merge info to propagate when sessions are re-merged.
    """
    type: str = "merge"
    merge_id: str = ""  # UUID for this merge event
    child_session_id: str = ""  # The fork session that was merged
    fork_name: str = ""  # Name of the fork
    message: str = ""  # Summary of what was accomplished in the fork


@dataclass
class SlideBlock:
    """Slide content for presentation mode.

    Slides are a first-class turn type that can be:
    - Created manually via :new-slide command
    - Generated by Claude via create_slide balloons-tool
    - Viewed in a dedicated Slides tab
    - Presented fullscreen in presentation mode
    """
    type: str = "slide"
    title: str = ""  # Slide title, max ~50 chars for 1080p
    content: str = ""  # Markdown body, max ~10 lines for 1080p
    notes: str = ""  # Speaker notes (not shown in presentation)


@dataclass
class ArchiveSummary:
    """Structured summary of archived content.

    Generated by LLM with specific prompt to capture:
    - What files were modified
    - What work was done
    - Key decisions made
    """
    files_modified: list[str] = field(default_factory=list)  # e.g., ["core/archiver.py (created)", "models.py (modified)"]
    work_done: str = ""  # 1-3 sentence description of what was accomplished
    key_decisions: list[str] = field(default_factory=list)  # Important design decisions


@dataclass
class ArchiveBlock:
    """Marker for archived turns stored in an external file.

    When turns are archived, they are replaced with a single message containing
    this block. The original messages are stored in a file and can be rehydrated.
    """
    type: str = "archive"
    archive_id: str = ""  # UUID for this archive
    file_path: str = ""  # Path to the archived content file
    summary: str = ""  # Plain text summary (legacy/fallback)
    structured_summary: Optional[ArchiveSummary] = None  # Structured summary
    turn_start: int = 0  # Original turn index (start, inclusive)
    turn_end: int = 0  # Original turn index (end, exclusive)
    message_count: int = 0  # Number of archived messages
    token_estimate: int = 0  # Estimated tokens saved by archiving

    def get_display_summary(self) -> str:
        """Get a display-friendly summary string."""
        if self.structured_summary:
            parts = []
            if self.structured_summary.work_done:
                parts.append(self.structured_summary.work_done)
            if self.structured_summary.files_modified:
                files = ", ".join(self.structured_summary.files_modified[:3])
                if len(self.structured_summary.files_modified) > 3:
                    files += f" (+{len(self.structured_summary.files_modified) - 3} more)"
                parts.append(f"Files: {files}")
            return " | ".join(parts) if parts else self.summary
        return self.summary


# Union type for all content block types
ContentBlock = Union[TextBlock, ToolUseBlock, ToolResultBlock, InterruptionBlock, ErrorBlock, LinkBlock, ForkBlock, MergeBlock, ArchiveBlock, SlideBlock]


@dataclass
class Message:
    role: str  # "user", "assistant", or "tool"
    content: str  # Text-only summary for display/backwards compat
    content_blocks: list[ContentBlock] = field(default_factory=list)  # Rich content
    tokens: int = 0
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    context_mode: ContextMode = ContextMode.COMPRESS
    summary: str = ""  # Cached summary for SUMMARIZE mode
    exchange_id: Optional[str] = None  # Groups turns in an agentic loop (user prompt + all responses)


@dataclass
class TextDelta:
    text: str
    raw: dict = field(default_factory=dict)


@dataclass
class ResultEvent:
    input_tokens: int
    output_tokens: int
    total_cost_usd: float
    context_window: int = 200000
    raw: dict = field(default_factory=dict)


@dataclass
class InitEvent:
    model: str
    session_id: str
    context_window: int
    raw: dict = field(default_factory=dict)


@dataclass
class RawEvent:
    """Raw JSON event for inspection (non-parsed events)."""
    data: dict


@dataclass
class ToolUseStartEvent:
    """Tool use started - name known but input still streaming."""
    tool_use_id: str
    tool_name: str


@dataclass
class ToolInputDeltaEvent:
    """Partial tool input JSON."""
    tool_use_id: str
    partial_json: str


@dataclass
class ToolUseEvent:
    """Claude finished defining a tool use (input complete)."""
    tool_use_id: str
    tool_name: str
    tool_input: dict


@dataclass
class ToolResultEvent:
    """Result from a tool use."""
    tool_use_id: str
    result: str
