import asyncio
import json
import time
import uuid
import os
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path
from typing import Optional, AsyncIterator

import aiofiles

from models import Message, TextBlock, ToolUseBlock, ToolResultBlock, InterruptionBlock, ErrorBlock, LinkBlock, ForkBlock, MergeBlock, MergedToBlock, ArchiveBlock, ArchiveSummary, SlideBlock, ReviewBlock, ContentBlock, ContextMode, QueuedMessage, MessageQueue, Turn

# Rust storage availability (checked lazily to avoid circular imports)
_rust_storage_checked = False
_rust_storage_available = False
_rust_storage: Optional[object] = None  # Will be AsyncStorage when initialized


def _get_storage():
    """Get or create the singleton Rust storage instance."""
    global _rust_storage
    if _rust_storage is None:
        from core.async_storage import AsyncStorage
        _rust_storage = AsyncStorage()
    return _rust_storage


# Legacy paths - kept for cleanup only (can be used to delete old JSON files)
SESSIONS_DIR = Path.home() / ".balloons" / "sessions"
INDEX_FILE = SESSIONS_DIR / "index.json"


# Per-session save locks to prevent concurrent writes
_session_save_locks: dict[str, asyncio.Lock] = {}


def _get_save_lock(session_id: str) -> asyncio.Lock:
    """Get or create a lock for saving a specific session."""
    if session_id not in _session_save_locks:
        _session_save_locks[session_id] = asyncio.Lock()
    return _session_save_locks[session_id]


@dataclass
class Session:
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    created: str = field(default_factory=lambda: datetime.now().isoformat())
    last_modified: str = field(default_factory=lambda: datetime.now().isoformat())
    model: str = ""
    turns: list[Turn] = field(default_factory=list)  # One content block per turn
    _messages_deprecated: list[Message] = field(default_factory=list)  # Migration only, not used

    total_input_tokens: int = 0
    total_output_tokens: int = 0
    total_cost: float = 0.0
    context_window: int = 200000
    # Session forking fields
    parent_id: Optional[str] = None
    children: list[dict] = field(default_factory=list)  # [{session_id, status, return_condition, prompt}]
    returned: bool = False
    return_condition: str = "manual"
    # Working directories for the session (resolved absolute paths)
    working_directories: list[str] = field(default_factory=list)
    # Session title and summary (generated by LLM)
    title: str = ""
    summary: str = ""
    # Fork/merge tracking (new model)
    fork_name: str = ""  # User-friendly name for this fork (e.g., "auth-bug")
    fork_status: str = "active"  # "active", "merged", "abandoned"
    fork_point_turn: int = -1  # Turn index in parent where fork was created
    merge_point_turn: int = -1  # Turn index in parent where merge happened
    merge_message: str = ""  # User's summary when merging back
    # Backend configuration
    backend_name: str = ""  # Name of backend to use (empty = default)
    # Cached context token count (calculated from compiled context, not turn content)
    # This is recalculated when turns change and saved to avoid expensive recomputation on load
    cached_context_tokens: int = 0
    # Message queue for prompts submitted during streaming
    message_queue: MessageQueue = field(default_factory=MessageQueue)
    # Note: Links are stored as LinkBlock content blocks in messages (turn-based).
    # The legacy `links` field has been removed - old sessions with links data
    # will have those links ignored (they were never actively used).

    @property
    def total_tokens(self) -> int:
        return self.total_input_tokens + self.total_output_tokens

    def add_turn(
        self,
        role: str,
        content_block: ContentBlock,
        tokens: int = 0,
        exchange_id: str | None = None,
        timestamp: str | None = None,
        context_mode: ContextMode = ContextMode.COMPRESS,
    ) -> Turn:
        """Add a single turn with one content block.

        Args:
            role: "user", "assistant", "tool", or "system"
            content_block: Single content block (TextBlock, ToolUseBlock, etc.)
            tokens: Token count for this turn
            exchange_id: Groups turns in an agentic loop (user prompt + all responses)
            timestamp: Optional timestamp (defaults to now)
            context_mode: How to handle in context compilation
        """
        turn = Turn(
            role=role,
            content_block=content_block,
            tokens=tokens,
            exchange_id=exchange_id,
            timestamp=timestamp or datetime.now().isoformat(),
            context_mode=context_mode,
        )
        self.turns.append(turn)
        return turn

    def add_message(
        self,
        role: str,
        content: str,
        content_blocks: list[ContentBlock] | None = None,
        tokens: int = 0,
        exchange_id: str | None = None,
    ) -> Turn:
        """DEPRECATED: Add a message with optional rich content blocks.

        Use add_turn() instead for new code. This method exists for backwards
        compatibility and will add turns internally.

        Args:
            role: "user", "assistant", or "tool"
            content: Text-only summary for display/backwards compat
            content_blocks: Rich content blocks (TextBlock, ToolUseBlock, etc.)
            tokens: Token count for this message
            exchange_id: Groups turns in an agentic loop (user prompt + all responses)

        Returns:
            The last Turn added (for backwards compat, callers may expect a message-like object)
        """
        if content_blocks is None:
            # Default to a single text block
            content_blocks = [TextBlock(text=content)] if content else []

        # Add each content block as a separate turn
        timestamp = datetime.now().isoformat()
        last_turn = None
        for i, block in enumerate(content_blocks):
            # Only first block gets tokens (avoid double counting)
            block_tokens = tokens if i == 0 else 0
            last_turn = self.add_turn(
                role=role,
                content_block=block,
                tokens=block_tokens,
                exchange_id=exchange_id,
                timestamp=timestamp,
            )

        # Return last turn (messages field is no longer populated)
        return last_turn

    def update_usage(self, input_tokens: int, output_tokens: int, cost: float, context_window: int = 0):
        self.total_input_tokens += input_tokens
        self.total_output_tokens += output_tokens
        self.total_cost += cost
        if context_window:
            self.context_window = context_window

    def add_child(self, child_id: str, prompt: str, return_condition: str = "manual", name: str = "", fork_point: int = -1) -> None:
        """Register a child session (fork) spawned from this session."""
        self.children.append({
            "session_id": child_id,
            "status": "active",
            "return_condition": return_condition,
            "prompt": prompt,
            "name": name,
            "fork_point": fork_point,  # Turn index where fork was created
            "merge_point": -1,  # Will be set when merged
        })

    def mark_child_returned(self, child_id: str) -> None:
        """Mark a child session as returned. (Legacy - use mark_child_merged)"""
        self.mark_child_merged(child_id)

    def mark_child_merged(self, child_id: str, merge_point: int = -1) -> None:
        """Mark a child fork as merged."""
        for child in self.children:
            if child["session_id"] == child_id:
                child["status"] = "merged"
                if merge_point >= 0:
                    child["merge_point"] = merge_point
                break

    async def get_parent_async(self) -> Optional["Session"]:
        """Load and return the parent session if this is a child (async version)."""
        if not self.parent_id:
            return None
        return await Session.load_async(self.parent_id)

    def is_child_session(self) -> bool:
        """Check if this session is a child of another session."""
        return self.parent_id is not None

    def is_fork(self) -> bool:
        """Check if this session is a fork (has parent and can merge back)."""
        return self.parent_id is not None

    def is_merged(self) -> bool:
        """Check if this fork has been merged."""
        return self.fork_status == "merged"

    def is_read_only(self) -> bool:
        """Check if this session is read-only.

        Merged forks are NOT read-only. They can continue to be edited
        and re-merged any number of times. Each merge creates a new
        merge marker capturing work done since the last merge.
        """
        return False

    def check_auto_return(self, response_content: str) -> bool:
        """Check if auto-return condition is met for a child session.

        Args:
            response_content: The assistant's response text to check

        Returns:
            True if the auto-return condition is satisfied
        """
        if not self.is_child_session():
            return False

        condition = self.return_condition

        if condition == "manual":
            return False

        if condition == "done":
            # Look for completion indicators
            done_indicators = [
                "task complete",
                "task is complete",
                "completed the task",
                "finished",
                "done",
                "all set",
            ]
            lower_content = response_content.lower()
            for indicator in done_indicators:
                if indicator in lower_content:
                    return True
            return False

        if condition.startswith("turns:"):
            try:
                max_turns = int(condition.split(":")[1])
                # Count assistant turns in this child session
                assistant_count = sum(1 for t in self.turns if t.role == "assistant")
                # +1 for the current response not yet saved
                return assistant_count + 1 >= max_turns
            except (ValueError, IndexError):
                return False

        return False

    def mark_merged(self, message: str, merge_turn: int) -> None:
        """Mark this fork as merged."""
        self.fork_status = "merged"
        self.merge_message = message
        self.merge_point_turn = merge_turn

    def get_fork_display_name(self) -> str:
        """Get display name for this fork."""
        if self.fork_name:
            return self.fork_name
        elif self.title:
            return self.title
        else:
            return self.id[:8]

    def get_last_exchange_id(self) -> str | None:
        """Get the exchange_id of the most recent turn that has one.

        Useful for grouping marker turns (fork/merge/link) with their
        triggering proposal exchange.
        """
        for turn in reversed(self.turns):
            if turn.exchange_id:
                return turn.exchange_id
        return None

    def delete_turn(self, turn_index: int) -> bool:
        """Delete a turn from the session history.

        Returns True if deleted, False if index invalid.
        """
        if 0 <= turn_index < len(self.turns):
            del self.turns[turn_index]
            return True
        return False

    def delete_turns(self, turn_indices: list[int]) -> int:
        """Delete multiple turns from the session history.

        Deletes in reverse order to preserve indices during deletion.

        Args:
            turn_indices: List of turn indices to delete

        Returns:
            Number of turns actually deleted
        """
        # Sort in reverse order so deleting doesn't affect subsequent indices
        sorted_indices = sorted(set(turn_indices), reverse=True)
        deleted_count = 0
        for idx in sorted_indices:
            if 0 <= idx < len(self.turns):
                del self.turns[idx]
                deleted_count += 1
        return deleted_count

    def delete(self) -> bool:
        """Delete this session from storage (sync version).

        Returns True if deleted, False if not found.
        Note: Prefer delete_async() to avoid blocking the UI.
        """
        try:
            asyncio.get_running_loop()
            raise RuntimeError(
                "Session.delete() called from async context. "
                "Use 'await session.delete_async()' instead."
            )
        except RuntimeError as e:
            if "no running event loop" not in str(e).lower():
                raise
            return asyncio.run(self.delete_async())

    async def delete_async(self) -> bool:
        """Delete this session from storage.

        Returns True if deleted, False if not found.
        """
        storage = _get_storage()
        try:
            await storage.delete_session(self.id)
            return True
        except Exception:
            return False

    def get_active_forks(self) -> list[dict]:
        """Get list of active (non-merged) child forks."""
        return [c for c in self.children if c.get("status") == "active"]

    def get_all_forks(self) -> list[dict]:
        """Get all child forks (active and merged)."""
        return self.children

    def add_link_turn(
        self,
        link_id: str,
        linked_session_id: str,
        summary: str,
        exchange_id: str | None = None,
    ) -> Turn:
        """Add a link as a turn in the conversation.

        Args:
            exchange_id: If provided, groups this marker with the link proposal exchange
        """
        link_block = LinkBlock(
            link_id=link_id,
            linked_session_id=linked_session_id,
            summary=summary,
            is_orphaned=False,
        )
        return self.add_turn(role="system", content_block=link_block, exchange_id=exchange_id)

    # =========================================================================
    # Fork/Merge Turn Methods
    # =========================================================================

    def add_fork_turn(
        self,
        fork_id: str,
        child_session_id: str,
        fork_name: str,
        prompt: str,
        status: str = "active",
        exchange_id: str | None = None,
    ) -> Turn:
        """Add a fork marker as a turn in the conversation.

        This records where a fork was created, allowing nested fork history
        to propagate through merges.

        Args:
            exchange_id: If provided, groups this marker with the fork proposal exchange
        """
        fork_block = ForkBlock(
            fork_id=fork_id,
            child_session_id=child_session_id,
            fork_name=fork_name,
            prompt=prompt,
            status=status,
        )
        return self.add_turn(role="system", content_block=fork_block, exchange_id=exchange_id)

    def add_merge_turn(
        self,
        merge_id: str,
        child_session_id: str,
        fork_name: str,
        message: str,
        files_changed: list[str] | None = None,
        key_accomplishments: list[str] | None = None,
        reason: str = "",
        exchange_id: str | None = None,
    ) -> Turn:
        """Add a merge marker as a turn in the conversation.

        This records where a fork was merged back, including the merge summary.
        Nested merge blocks propagate through subsequent merges.

        Args:
            exchange_id: If provided, groups this marker with the merge proposal exchange
        """
        merge_block = MergeBlock(
            merge_id=merge_id,
            child_session_id=child_session_id,
            fork_name=fork_name,
            message=message,
            files_changed=files_changed or [],
            key_accomplishments=key_accomplishments or [],
            reason=reason,
        )
        return self.add_turn(role="system", content_block=merge_block, exchange_id=exchange_id)

    def add_merged_to_turn(
        self,
        merge_id: str,
        parent_session_id: str,
        parent_name: str,
        parent_turn: int,
        message: str,
        files_changed: list[str] | None = None,
        key_accomplishments: list[str] | None = None,
        reason: str = "",
        exchange_id: str | None = None,
    ) -> Turn:
        """Add a 'merged to' marker as the final turn in a fork.

        This records that this fork was merged back to its parent.
        Counterpart to add_merge_turn which is called on the parent.

        Args:
            exchange_id: If provided, groups this marker with the merge proposal exchange
        """
        merged_to_block = MergedToBlock(
            merge_id=merge_id,
            parent_session_id=parent_session_id,
            parent_name=parent_name,
            parent_turn=parent_turn,
            message=message,
            files_changed=files_changed or [],
            key_accomplishments=key_accomplishments or [],
            reason=reason,
        )
        return self.add_turn(role="system", content_block=merged_to_block, exchange_id=exchange_id)

    def add_review_turn(
        self,
        review_id: str,
        child_session_id: str,
        model_under_review: str,
        status: str = "active",
        exchange_id: str | None = None,
    ) -> Turn:
        """Add a review marker as a turn in the conversation.

        This records that a quality review was initiated at this point.

        Args:
            review_id: UUID for this review
            child_session_id: The review session's ID
            model_under_review: Backend name of model being evaluated
            status: "active", "completed", or "abandoned"
            exchange_id: If provided, groups this marker with other turns
        """
        review_block = ReviewBlock(
            review_id=review_id,
            child_session_id=child_session_id,
            model_under_review=model_under_review,
            status=status,
        )
        return self.add_turn(role="system", content_block=review_block, exchange_id=exchange_id)

    def update_review_status(
        self,
        child_session_id: str,
        status: str,
        overall_score: float = 0.0,
        task_category: str = "",
        task_description: str = "",
    ) -> bool:
        """Update the status and results of a review block.

        Returns True if found and updated, False if not found.
        """
        for turn in self.turns:
            if isinstance(turn.content_block, ReviewBlock) and turn.content_block.child_session_id == child_session_id:
                turn.content_block.status = status
                turn.content_block.overall_score = overall_score
                turn.content_block.task_category = task_category
                turn.content_block.task_description = task_description
                return True
        return False

    def get_all_review_blocks(self) -> list[tuple[int, ReviewBlock]]:
        """Get all review blocks with their turn indices.

        Returns:
            List of (turn_index, ReviewBlock) tuples
        """
        reviews = []
        for i, turn in enumerate(self.turns):
            if isinstance(turn.content_block, ReviewBlock):
                reviews.append((i, turn.content_block))
        return reviews

    def get_merged_to_block(self) -> Optional[MergedToBlock]:
        """Get the MergedToBlock if this session was merged.

        Returns:
            MergedToBlock if found, None otherwise
        """
        for turn in reversed(self.turns):
            if isinstance(turn.content_block, MergedToBlock):
                return turn.content_block
        return None

    def get_all_fork_blocks(self) -> list[tuple[int, ForkBlock]]:
        """Get all fork blocks with their turn indices.

        Returns:
            List of (turn_index, ForkBlock) tuples
        """
        forks = []
        for i, turn in enumerate(self.turns):
            if isinstance(turn.content_block, ForkBlock):
                forks.append((i, turn.content_block))
        return forks

    def get_all_merge_blocks(self) -> list[tuple[int, MergeBlock]]:
        """Get all merge blocks with their turn indices.

        Returns:
            List of (turn_index, MergeBlock) tuples
        """
        merges = []
        for i, turn in enumerate(self.turns):
            if isinstance(turn.content_block, MergeBlock):
                merges.append((i, turn.content_block))
        return merges

    def update_fork_status(self, child_session_id: str, status: str) -> bool:
        """Update the status of a fork block.

        Returns True if found and updated, False if not found.
        """
        for turn in self.turns:
            if isinstance(turn.content_block, ForkBlock) and turn.content_block.child_session_id == child_session_id:
                turn.content_block.status = status
                return True
        return False

    def get_all_link_ids(self) -> list[str]:
        """Get all link IDs from LinkBlock turns."""
        link_ids = []
        for turn in self.turns:
            if isinstance(turn.content_block, LinkBlock):
                link_ids.append(turn.content_block.link_id)
        return link_ids

    def get_all_active_links(self) -> list[dict]:
        """Get all non-orphaned links from LinkBlock turns."""
        active = []
        for turn in self.turns:
            block = turn.content_block
            if isinstance(block, LinkBlock) and not block.is_orphaned:
                active.append({
                    "link_id": block.link_id,
                    "linked_session_id": block.linked_session_id,
                    "summary": block.summary,
                    "is_orphaned": block.is_orphaned,
                })
        return active

    def mark_link_orphaned(self, link_id: str) -> None:
        """Mark a link as orphaned (linked session was deleted)."""
        for turn in self.turns:
            if isinstance(turn.content_block, LinkBlock) and turn.content_block.link_id == link_id:
                turn.content_block.is_orphaned = True
                return

    def has_active_links(self) -> bool:
        """Check if this session has any non-orphaned links."""
        return len(self.get_all_active_links()) > 0

    # =========================================================================
    # Archive Methods
    # =========================================================================

    def get_all_archives(self) -> list[tuple[int, ArchiveBlock]]:
        """Get all archive blocks with their turn indices.

        Returns:
            List of (turn_index, ArchiveBlock) tuples
        """
        archives = []
        for i, turn in enumerate(self.turns):
            if isinstance(turn.content_block, ArchiveBlock):
                archives.append((i, turn.content_block))
        return archives

    def archive_turns(self, turn_start: int, turn_end: int, summary: str) -> ArchiveBlock:
        """Archive a range of turns to a file, replacing them with an ArchiveBlock.

        Args:
            turn_start: Start index (inclusive)
            turn_end: End index (exclusive)
            summary: LLM-generated summary of the archived content

        Returns:
            The ArchiveBlock that was inserted

        Raises:
            ArchiveError: If indices are invalid or archive fails
        """
        from core.archiver import Archiver
        archiver = Archiver()
        archive_block, new_turns = archiver.archive_turns(
            session_id=self.id,
            turns=self.turns,
            turn_start=turn_start,
            turn_end=turn_end,
            summary=summary,
        )
        self.turns = new_turns
        return archive_block

    def rehydrate_archive(self, archive_turn_index: int) -> int:
        """Rehydrate an archived turn, restoring the original turns.

        Args:
            archive_turn_index: Index of the turn containing the ArchiveBlock

        Returns:
            Number of turns restored

        Raises:
            ArchiveError: If the turn doesn't contain an archive block or rehydration fails
        """
        from core.archiver import Archiver
        archiver = Archiver()

        # Get the archive block to know how many turns will be restored
        archive_turn = self.turns[archive_turn_index]
        if not isinstance(archive_turn.content_block, ArchiveBlock):
            from core.archiver import ArchiveError
            raise ArchiveError(f"Turn {archive_turn_index} does not contain an archive block")

        archive_block = archive_turn.content_block
        new_turns = archiver.rehydrate(self.turns, archive_turn_index)
        self.turns = new_turns
        return archive_block.message_count

    def has_archives(self) -> bool:
        """Check if this session has any archived turns."""
        return len(self.get_all_archives()) > 0

    # =========================================================================
    # Slide Methods
    # =========================================================================

    def add_slide_turn(
        self,
        title: str,
        content: str,
        notes: str = "",
    ) -> Turn:
        """Add a slide as a turn in the conversation.

        Args:
            title: Slide title (max ~50 chars for 1080p)
            content: Markdown body (max ~10 lines for 1080p)
            notes: Optional speaker notes (not shown in presentation)

        Returns:
            The Turn containing the SlideBlock
        """
        slide_block = SlideBlock(
            title=title,
            content=content,
            notes=notes,
        )
        return self.add_turn(role="slide", content_block=slide_block)

    def get_all_slides(self) -> list[tuple[int, SlideBlock]]:
        """Get all slide blocks with their turn indices.

        Returns:
            List of (turn_index, SlideBlock) tuples in order of appearance
        """
        slides = []
        for i, turn in enumerate(self.turns):
            if isinstance(turn.content_block, SlideBlock):
                slides.append((i, turn.content_block))
        return slides

    def get_slide_count(self) -> int:
        """Get the number of slides in this session."""
        return sum(1 for t in self.turns if isinstance(t.content_block, SlideBlock))

    def has_slides(self) -> bool:
        """Check if this session has any slides."""
        return self.get_slide_count() > 0

    def update_slide(self, turn_index: int, title: str = None, content: str = None, notes: str = None) -> bool:
        """Update an existing slide's content.

        Args:
            turn_index: Index of the turn containing the slide
            title: New title (None to keep existing)
            content: New content (None to keep existing)
            notes: New notes (None to keep existing)

        Returns:
            True if updated, False if turn doesn't exist or isn't a slide
        """
        if turn_index < 0 or turn_index >= len(self.turns):
            return False
        turn = self.turns[turn_index]
        if not isinstance(turn.content_block, SlideBlock):
            return False
        if title is not None:
            turn.content_block.title = title
        if content is not None:
            turn.content_block.content = content
        if notes is not None:
            turn.content_block.notes = notes
        return True

    @property
    def working_directory(self) -> Optional[str]:
        """Get the current working directory (first in list), or None if not set."""
        return self.working_directories[0] if self.working_directories else None

    def set_working_directory(self, path: str) -> None:
        """Set the working directory, resolving to absolute canonical path."""
        resolved = str(Path(path).resolve())
        if self.working_directories:
            self.working_directories[0] = resolved
        else:
            self.working_directories.append(resolved)

    def _serialize_content_block(self, block: ContentBlock) -> dict:
        """Serialize a content block to a dict."""
        if isinstance(block, TextBlock):
            return {"type": "text", "text": block.text}
        elif isinstance(block, ToolUseBlock):
            return {"type": "tool_use", "id": block.id, "name": block.name, "input": block.input}
        elif isinstance(block, ToolResultBlock):
            return {"type": "tool_result", "tool_use_id": block.tool_use_id, "content": block.content, "is_error": block.is_error}
        elif isinstance(block, InterruptionBlock):
            return {"type": "interruption", "reason": block.reason}
        elif isinstance(block, ErrorBlock):
            return {
                "type": "error",
                "reason": block.reason,
                "partial_tool_name": block.partial_tool_name,
                "partial_tool_input": block.partial_tool_input,
                "details": block.details,
            }
        elif isinstance(block, LinkBlock):
            return {
                "type": "link",
                "link_id": block.link_id,
                "linked_session_id": block.linked_session_id,
                "summary": block.summary,
                "is_orphaned": block.is_orphaned,
            }
        elif isinstance(block, ForkBlock):
            return {
                "type": "fork",
                "fork_id": block.fork_id,
                "child_session_id": block.child_session_id,
                "fork_name": block.fork_name,
                "prompt": block.prompt,
                "status": block.status,
            }
        elif isinstance(block, MergeBlock):
            return {
                "type": "merge",
                "merge_id": block.merge_id,
                "child_session_id": block.child_session_id,
                "fork_name": block.fork_name,
                "message": block.message,
                "files_changed": block.files_changed,
                "key_accomplishments": block.key_accomplishments,
                "reason": block.reason,
            }
        elif isinstance(block, MergedToBlock):
            return {
                "type": "merged_to",
                "merge_id": block.merge_id,
                "parent_session_id": block.parent_session_id,
                "parent_name": block.parent_name,
                "parent_turn": block.parent_turn,
                "message": block.message,
                "files_changed": block.files_changed,
                "key_accomplishments": block.key_accomplishments,
                "reason": block.reason,
            }
        elif isinstance(block, ArchiveBlock):
            data = {
                "type": "archive",
                "archive_id": block.archive_id,
                "file_path": block.file_path,
                "summary": block.summary,
                "turn_start": block.turn_start,
                "turn_end": block.turn_end,
                "message_count": block.message_count,
                "token_estimate": block.token_estimate,
            }
            if block.structured_summary:
                data["structured_summary"] = {
                    "files_modified": block.structured_summary.files_modified,
                    "work_done": block.structured_summary.work_done,
                    "key_decisions": block.structured_summary.key_decisions,
                }
            return data
        elif isinstance(block, SlideBlock):
            return {
                "type": "slide",
                "title": block.title,
                "content": block.content,
                "notes": block.notes,
            }
        elif isinstance(block, ReviewBlock):
            return {
                "type": "review",
                "review_id": block.review_id,
                "child_session_id": block.child_session_id,
                "model_under_review": block.model_under_review,
                "status": block.status,
                "overall_score": block.overall_score,
                "task_category": block.task_category,
                "task_description": block.task_description,
            }
        return {"type": "unknown"}

    def _serialize_turn(self, turn: Turn) -> dict:
        """Serialize a turn to a dict."""
        data = {
            "role": turn.role,
            "content_block": self._serialize_content_block(turn.content_block),
            "tokens": turn.tokens,
            "timestamp": turn.timestamp,
            "context_mode": turn.context_mode.value,
            "summary": turn.summary,
        }
        if turn.exchange_id:
            data["exchange_id"] = turn.exchange_id
        return data

    def _serialize_message(self, msg: Message) -> dict:
        """Serialize a message with content blocks. DEPRECATED - for migration only."""
        data = {
            "role": msg.role,
            "content": msg.content,
            "content_blocks": [self._serialize_content_block(b) for b in msg.content_blocks],
            "tokens": msg.tokens,
            "timestamp": msg.timestamp,
            "context_mode": msg.context_mode.value,
            "summary": msg.summary,
        }
        # Only include exchange_id if set (backwards compat)
        if msg.exchange_id:
            data["exchange_id"] = msg.exchange_id
        return data

    def _build_save_data(self) -> dict:
        """Build the data dict for saving."""
        self.last_modified = datetime.now().isoformat()
        return {
            "id": self.id,
            "created": self.created,
            "last_modified": self.last_modified,
            "model": self.model,
            "turns": [self._serialize_turn(t) for t in self.turns],
            "messages": [],  # Truncated - data now in turns
            "total_input_tokens": self.total_input_tokens,
            "total_output_tokens": self.total_output_tokens,
            "total_cost": self.total_cost,
            "context_window": self.context_window,
            "parent_id": self.parent_id,
            "children": self.children,
            "returned": self.returned,
            "return_condition": self.return_condition,
            "working_directories": self.working_directories,
            "title": self.title,
            "summary": self.summary,
            # Fork/merge tracking
            "fork_name": self.fork_name,
            "fork_status": self.fork_status,
            "fork_point_turn": self.fork_point_turn,
            "merge_point_turn": self.merge_point_turn,
            "merge_message": self.merge_message,
            "backend_name": self.backend_name,
            "cached_context_tokens": self.cached_context_tokens,
            "message_queue": self.message_queue.to_dict() if self.message_queue else {},
        }

    def save(self):
        """Save session to storage (sync version).

        For async code, prefer save_async() to avoid blocking.
        """
        try:
            asyncio.get_running_loop()
            raise RuntimeError(
                "Session.save() called from async context. "
                "Use 'await session.save_async()' instead."
            )
        except RuntimeError as e:
            if "no running event loop" not in str(e).lower():
                raise
            asyncio.run(self.save_async())

    async def save_async(self):
        """Save session to storage."""
        storage = _get_storage()
        await storage.save_session(self)

    @classmethod
    def _load_working_directories(cls, data: dict) -> list[str]:
        """Load working directories with backwards compatibility for old format."""
        # New format: list of paths
        if "working_directories" in data:
            return data["working_directories"]
        # Old format: single path string
        if "working_directory" in data and data["working_directory"]:
            return [data["working_directory"]]
        return []

    @classmethod
    def _deserialize_content_block(cls, data: dict) -> ContentBlock:
        """Deserialize a content block from a dict."""
        block_type = data.get("type", "text")
        if block_type == "text":
            return TextBlock(text=data.get("text", ""))
        elif block_type == "tool_use":
            return ToolUseBlock(
                id=data.get("id", ""),
                name=data.get("name", ""),
                input=data.get("input", {}),
            )
        elif block_type == "tool_result":
            return ToolResultBlock(
                tool_use_id=data.get("tool_use_id", ""),
                content=data.get("content", ""),
                is_error=data.get("is_error", False),
            )
        elif block_type == "interruption":
            return InterruptionBlock(
                reason=data.get("reason", "user_cancelled"),
            )
        elif block_type == "error":
            return ErrorBlock(
                reason=data.get("reason", "stream_error"),
                partial_tool_name=data.get("partial_tool_name", ""),
                partial_tool_input=data.get("partial_tool_input", ""),
                details=data.get("details", ""),
            )
        elif block_type == "link":
            return LinkBlock(
                link_id=data.get("link_id", ""),
                linked_session_id=data.get("linked_session_id", ""),
                summary=data.get("summary", ""),
                is_orphaned=data.get("is_orphaned", False),
            )
        elif block_type == "fork":
            return ForkBlock(
                fork_id=data.get("fork_id", ""),
                child_session_id=data.get("child_session_id", ""),
                fork_name=data.get("fork_name", ""),
                prompt=data.get("prompt", ""),
                status=data.get("status", "active"),
            )
        elif block_type == "merge":
            return MergeBlock(
                merge_id=data.get("merge_id", ""),
                child_session_id=data.get("child_session_id", ""),
                fork_name=data.get("fork_name", ""),
                message=data.get("message", ""),
                files_changed=data.get("files_changed", []),
                key_accomplishments=data.get("key_accomplishments", []),
                reason=data.get("reason", ""),
            )
        elif block_type == "merged_to":
            return MergedToBlock(
                merge_id=data.get("merge_id", ""),
                parent_session_id=data.get("parent_session_id", ""),
                parent_name=data.get("parent_name", ""),
                parent_turn=data.get("parent_turn", 0),
                message=data.get("message", ""),
                files_changed=data.get("files_changed", []),
                key_accomplishments=data.get("key_accomplishments", []),
                reason=data.get("reason", ""),
            )
        elif block_type == "archive":
            structured_summary = None
            if "structured_summary" in data:
                ss = data["structured_summary"]
                structured_summary = ArchiveSummary(
                    files_modified=ss.get("files_modified", []),
                    work_done=ss.get("work_done", ""),
                    key_decisions=ss.get("key_decisions", []),
                )
            return ArchiveBlock(
                archive_id=data.get("archive_id", ""),
                file_path=data.get("file_path", ""),
                summary=data.get("summary", ""),
                structured_summary=structured_summary,
                turn_start=data.get("turn_start", 0),
                turn_end=data.get("turn_end", 0),
                message_count=data.get("message_count", 0),
                token_estimate=data.get("token_estimate", 0),
            )
        elif block_type == "slide":
            return SlideBlock(
                title=data.get("title", ""),
                content=data.get("content", ""),
                notes=data.get("notes", ""),
            )
        elif block_type == "review":
            return ReviewBlock(
                review_id=data.get("review_id", ""),
                child_session_id=data.get("child_session_id", ""),
                model_under_review=data.get("model_under_review", ""),
                status=data.get("status", "active"),
                overall_score=data.get("overall_score", 0.0),
                task_category=data.get("task_category", ""),
                task_description=data.get("task_description", ""),
            )
        # Fallback to text
        return TextBlock(text=str(data))

    @classmethod
    def _deserialize_turn(cls, data: dict) -> Turn:
        """Deserialize a turn from a dict."""
        content_block = cls._deserialize_content_block(data.get("content_block", {"type": "text", "text": ""}))

        mode_str = data.get("context_mode", "compress")
        try:
            context_mode = ContextMode(mode_str)
        except ValueError:
            context_mode = ContextMode.COMPRESS

        return Turn(
            role=data["role"],
            content_block=content_block,
            tokens=data.get("tokens", 0),
            timestamp=data.get("timestamp", ""),
            context_mode=context_mode,
            summary=data.get("summary", ""),
            exchange_id=data.get("exchange_id"),
        )

    @classmethod
    def _build_session_from_data(cls, data: dict) -> "Session":
        """Build a Session object from loaded data dict."""
        # For backwards compat, use created if last_modified missing
        last_modified = data.get("last_modified", data.get("created", ""))
        session = cls(
            id=data["id"],
            created=data["created"],
            last_modified=last_modified,
            model=data.get("model", ""),
            total_input_tokens=data.get("total_input_tokens", 0),
            total_output_tokens=data.get("total_output_tokens", 0),
            total_cost=data.get("total_cost", 0.0),
            context_window=data.get("context_window", 200000),
            parent_id=data.get("parent_id"),
            children=data.get("children", []),
            returned=data.get("returned", False),
            return_condition=data.get("return_condition", "manual"),
            working_directories=cls._load_working_directories(data),
            title=data.get("title", ""),
            summary=data.get("summary", ""),
            # Fork/merge tracking
            fork_name=data.get("fork_name", ""),
            fork_status=data.get("fork_status", "active"),
            fork_point_turn=data.get("fork_point_turn", -1),
            merge_point_turn=data.get("merge_point_turn", -1),
            merge_message=data.get("merge_message", ""),
            backend_name=data.get("backend_name", ""),
            cached_context_tokens=data.get("cached_context_tokens", 0),
            message_queue=MessageQueue.from_dict(data.get("message_queue", {})),
        )

        # Load turns (new format)
        for t in data.get("turns", []):
            session.turns.append(cls._deserialize_turn(t))

        # Migration: if no turns but has messages, expand messages to turns
        if not session.turns and data.get("messages"):
            for m in data.get("messages", []):
                # Parse content_blocks if present, otherwise create from content
                raw_blocks = m.get("content_blocks", [])
                if raw_blocks:
                    content_blocks = [cls._deserialize_content_block(b) for b in raw_blocks]
                else:
                    # Backwards compat: create text block from content
                    content_blocks = [TextBlock(text=m.get("content", ""))] if m.get("content") else []

                # Parse context_mode
                mode_str = m.get("context_mode", "copy")
                try:
                    context_mode = ContextMode(mode_str)
                except ValueError:
                    context_mode = ContextMode.COPY

                # Expand each content block into a separate turn
                timestamp = m.get("timestamp", "")
                exchange_id = m.get("exchange_id")
                tokens = m.get("tokens", 0)

                for i, block in enumerate(content_blocks):
                    # Only first block gets tokens (avoid double counting)
                    block_tokens = tokens if i == 0 else 0
                    session.turns.append(Turn(
                        role=m["role"],
                        content_block=block,
                        tokens=block_tokens,
                        timestamp=timestamp,
                        context_mode=context_mode,
                        summary=m.get("summary", "") if i == 0 else "",
                        exchange_id=exchange_id,
                    ))

        return session

    @classmethod
    def load(cls, session_id: str) -> Optional["Session"]:
        """Load a session by ID (sync version).

        For async code, prefer load_async() to avoid blocking.
        """
        try:
            asyncio.get_running_loop()
            raise RuntimeError(
                "Session.load() called from async context. "
                "Use 'await Session.load_async()' instead."
            )
        except RuntimeError as e:
            if "no running event loop" not in str(e).lower():
                raise
            return asyncio.run(cls.load_async(session_id))

    @classmethod
    async def load_async(cls, session_id: str) -> Optional["Session"]:
        """Load a session by ID."""
        storage = _get_storage()
        return await storage.load_session(session_id)

    @classmethod
    def list_sessions(cls) -> list[dict]:
        """Return list of session metadata dicts (sync version).

        For async code, prefer list_sessions_async().
        Returns list of dicts with keys: id, name, created_at, updated_at, turn_count.
        """
        try:
            asyncio.get_running_loop()
            raise RuntimeError(
                "Session.list_sessions() called from async context. "
                "Use 'async for s in Session.list_sessions_async()' instead."
            )
        except RuntimeError as e:
            if "no running event loop" not in str(e).lower():
                raise
            storage = _get_storage()
            return asyncio.run(storage.list_sessions())

    @classmethod
    async def list_sessions_async(cls) -> AsyncIterator[dict]:
        """Async generator that yields session metadata dicts one at a time.

        Sessions are yielded in order of last_modified (most recent first).
        Yields dicts with keys: id, name, created_at, updated_at, turn_count.
        """
        storage = _get_storage()
        sessions = await storage.list_sessions()
        for metadata in sessions:
            yield metadata

    @classmethod
    def get_most_recent_session_id(cls) -> Optional[str]:
        """Get the ID of the most recently modified session (sync version).

        Returns None if no sessions exist.
        """
        try:
            asyncio.get_running_loop()
            raise RuntimeError(
                "Session.get_most_recent_session_id() called from async context. "
                "Use 'async for s in Session.list_sessions_async()' instead."
            )
        except RuntimeError as e:
            if "no running event loop" not in str(e).lower():
                raise
            storage = _get_storage()
            sessions = asyncio.run(storage.list_sessions())
        if sessions:
            return sessions[0]["id"]  # Already sorted by last_modified desc
        return None
