import json
import uuid
import os
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path
from typing import Optional

from models import Message, TextBlock, ToolUseBlock, ToolResultBlock, ContentBlock, ContextMode


SESSIONS_DIR = Path.home() / ".balloons" / "sessions"


@dataclass
class Session:
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    created: str = field(default_factory=lambda: datetime.now().isoformat())
    last_modified: str = field(default_factory=lambda: datetime.now().isoformat())
    model: str = ""
    messages: list[Message] = field(default_factory=list)
    total_input_tokens: int = 0
    total_output_tokens: int = 0
    total_cost: float = 0.0
    context_window: int = 200000
    # Session forking fields
    parent_id: Optional[str] = None
    children: list[dict] = field(default_factory=list)  # [{session_id, status, return_condition, prompt}]
    returned: bool = False
    return_condition: str = "manual"
    # Working directories for the session (resolved absolute paths)
    working_directories: list[str] = field(default_factory=list)
    # Session title and summary (generated by LLM)
    title: str = ""
    summary: str = ""
    # Fork/merge tracking (new model)
    fork_name: str = ""  # User-friendly name for this fork (e.g., "auth-bug")
    fork_status: str = "active"  # "active", "merged", "abandoned"
    fork_point_turn: int = -1  # Turn index in parent where fork was created
    merge_point_turn: int = -1  # Turn index in parent where merge happened
    merge_message: str = ""  # User's summary when merging back
    # Backend configuration
    backend_name: str = ""  # Name of backend to use (empty = default)
    # Bidirectional links to other sessions
    # Bidirectional links to other sessions
    links: list[dict] = field(default_factory=list)
    # Each link: {
    #   "link_id": str,           # UUID for this link pair (same in both sessions)
    #   "linked_session_id": str, # The other session's ID
    #   "link_point": int,        # Turn index where link appears in THIS session
    #   "summary": str,           # LLM-generated summary
    #   "created": str,           # ISO timestamp
    #   "is_orphaned": bool,      # True if linked session was deleted
    # }

    @property
    def total_tokens(self) -> int:
        return self.total_input_tokens + self.total_output_tokens

    def add_message(
        self,
        role: str,
        content: str,
        content_blocks: list[ContentBlock] | None = None,
        tokens: int = 0,
    ) -> Message:
        """Add a message with optional rich content blocks."""
        if content_blocks is None:
            # Default to a single text block
            content_blocks = [TextBlock(text=content)] if content else []
        msg = Message(role=role, content=content, content_blocks=content_blocks, tokens=tokens)
        self.messages.append(msg)
        return msg

    def update_usage(self, input_tokens: int, output_tokens: int, cost: float, context_window: int = 0):
        self.total_input_tokens += input_tokens
        self.total_output_tokens += output_tokens
        self.total_cost += cost
        if context_window:
            self.context_window = context_window

    def add_child(self, child_id: str, prompt: str, return_condition: str = "manual", name: str = "", fork_point: int = -1) -> None:
        """Register a child session (fork) spawned from this session."""
        self.children.append({
            "session_id": child_id,
            "status": "active",
            "return_condition": return_condition,
            "prompt": prompt,
            "name": name,
            "fork_point": fork_point,  # Turn index where fork was created
            "merge_point": -1,  # Will be set when merged
        })

    def mark_child_returned(self, child_id: str) -> None:
        """Mark a child session as returned. (Legacy - use mark_child_merged)"""
        self.mark_child_merged(child_id)

    def mark_child_merged(self, child_id: str, merge_point: int = -1) -> None:
        """Mark a child fork as merged."""
        for child in self.children:
            if child["session_id"] == child_id:
                child["status"] = "merged"
                if merge_point >= 0:
                    child["merge_point"] = merge_point
                break

    def get_parent(self) -> Optional["Session"]:
        """Load and return the parent session if this is a child."""
        if not self.parent_id:
            return None
        return Session.load(self.parent_id)

    def is_child_session(self) -> bool:
        """Check if this session is a child of another session."""
        return self.parent_id is not None

    def is_fork(self) -> bool:
        """Check if this session is a fork (has parent and can merge back)."""
        return self.parent_id is not None

    def is_merged(self) -> bool:
        """Check if this fork has been merged."""
        return self.fork_status == "merged"

    def is_read_only(self) -> bool:
        """Check if this session is read-only.

        Previously, merged forks were read-only. Now they can continue
        to be edited - the merge marker is just another turn that can
        be deleted, and re-merging is allowed if context advances.
        """
        return False

    def mark_merged(self, message: str, merge_turn: int) -> None:
        """Mark this fork as merged."""
        self.fork_status = "merged"
        self.merge_message = message
        self.merge_point_turn = merge_turn

    def get_fork_display_name(self) -> str:
        """Get display name for this fork."""
        if self.fork_name:
            return self.fork_name
        elif self.title:
            return self.title
        else:
            return self.id[:8]

    def delete_turn(self, turn_index: int) -> bool:
        """Delete a turn from the session history.

        Returns True if deleted, False if index invalid.
        """
        if 0 <= turn_index < len(self.messages):
            del self.messages[turn_index]
            return True
        return False

    def delete(self) -> bool:
        """Delete this session's file from disk.

        Returns True if deleted, False if file didn't exist.
        """
        path = SESSIONS_DIR / f"{self.id}.json"
        if path.exists():
            path.unlink()
            return True
        return False

    def get_active_forks(self) -> list[dict]:
        """Get list of active (non-merged) child forks."""
        return [c for c in self.children if c.get("status") == "active"]

    def get_all_forks(self) -> list[dict]:
        """Get all child forks (active and merged)."""
        return self.children

    def add_link(self, link_id: str, linked_session_id: str, link_point: int, summary: str) -> None:
        """Add a bidirectional link to another session."""
        self.links.append({
            "link_id": link_id,
            "linked_session_id": linked_session_id,
            "link_point": link_point,
            "summary": summary,
            "created": datetime.now().isoformat(),
            "is_orphaned": False,
        })

    def get_links(self) -> list[dict]:
        """Get all links from this session."""
        return self.links

    def get_active_links(self) -> list[dict]:
        """Get non-orphaned links from this session."""
        return [link for link in self.links if not link.get("is_orphaned", False)]

    def mark_link_orphaned(self, link_id: str) -> None:
        """Mark a link as orphaned (linked session was deleted)."""
        for link in self.links:
            if link["link_id"] == link_id:
                link["is_orphaned"] = True
                break

    def has_active_links(self) -> bool:
        """Check if this session has any non-orphaned links."""
        return len(self.get_active_links()) > 0

    @property
    def working_directory(self) -> Optional[str]:
        """Get the current working directory (first in list), or None if not set."""
        return self.working_directories[0] if self.working_directories else None

    def set_working_directory(self, path: str) -> None:
        """Set the working directory, resolving to absolute canonical path."""
        resolved = str(Path(path).resolve())
        if self.working_directories:
            self.working_directories[0] = resolved
        else:
            self.working_directories.append(resolved)

    def _serialize_content_block(self, block: ContentBlock) -> dict:
        """Serialize a content block to a dict."""
        if isinstance(block, TextBlock):
            return {"type": "text", "text": block.text}
        elif isinstance(block, ToolUseBlock):
            return {"type": "tool_use", "id": block.id, "name": block.name, "input": block.input}
        elif isinstance(block, ToolResultBlock):
            return {"type": "tool_result", "tool_use_id": block.tool_use_id, "content": block.content, "is_error": block.is_error}
        return {"type": "unknown"}

    def _serialize_message(self, msg: Message) -> dict:
        """Serialize a message with content blocks."""
        return {
            "role": msg.role,
            "content": msg.content,
            "content_blocks": [self._serialize_content_block(b) for b in msg.content_blocks],
            "tokens": msg.tokens,
            "timestamp": msg.timestamp,
            "context_mode": msg.context_mode.value,
            "summary": msg.summary,
        }

    def save(self):
        SESSIONS_DIR.mkdir(parents=True, exist_ok=True)
        path = SESSIONS_DIR / f"{self.id}.json"
        # Update last_modified timestamp on every save
        self.last_modified = datetime.now().isoformat()
        data = {
            "id": self.id,
            "created": self.created,
            "last_modified": self.last_modified,
            "model": self.model,
            "messages": [self._serialize_message(m) for m in self.messages],
            "total_input_tokens": self.total_input_tokens,
            "total_output_tokens": self.total_output_tokens,
            "total_cost": self.total_cost,
            "context_window": self.context_window,
            "parent_id": self.parent_id,
            "children": self.children,
            "returned": self.returned,
            "return_condition": self.return_condition,
            "working_directories": self.working_directories,
            "title": self.title,
            "summary": self.summary,
            # Fork/merge tracking
            "fork_name": self.fork_name,
            "fork_status": self.fork_status,
            "fork_point_turn": self.fork_point_turn,
            "merge_point_turn": self.merge_point_turn,
            "merge_message": self.merge_message,
            "backend_name": self.backend_name,
            "links": self.links,
        }
        path.write_text(json.dumps(data, indent=2))

    @classmethod
    def _load_working_directories(cls, data: dict) -> list[str]:
        """Load working directories with backwards compatibility for old format."""
        # New format: list of paths
        if "working_directories" in data:
            return data["working_directories"]
        # Old format: single path string
        if "working_directory" in data and data["working_directory"]:
            return [data["working_directory"]]
        return []

    @classmethod
    def _deserialize_content_block(cls, data: dict) -> ContentBlock:
        """Deserialize a content block from a dict."""
        block_type = data.get("type", "text")
        if block_type == "text":
            return TextBlock(text=data.get("text", ""))
        elif block_type == "tool_use":
            return ToolUseBlock(
                id=data.get("id", ""),
                name=data.get("name", ""),
                input=data.get("input", {}),
            )
        elif block_type == "tool_result":
            return ToolResultBlock(
                tool_use_id=data.get("tool_use_id", ""),
                content=data.get("content", ""),
                is_error=data.get("is_error", False),
            )
        # Fallback to text
        return TextBlock(text=str(data))

    @classmethod
    def load(cls, session_id: str) -> Optional["Session"]:
        path = SESSIONS_DIR / f"{session_id}.json"
        if not path.exists():
            return None
        data = json.loads(path.read_text())
        # For backwards compat, use created if last_modified missing
        last_modified = data.get("last_modified", data.get("created", ""))
        session = cls(
            id=data["id"],
            created=data["created"],
            last_modified=last_modified,
            model=data.get("model", ""),
            total_input_tokens=data.get("total_input_tokens", 0),
            total_output_tokens=data.get("total_output_tokens", 0),
            total_cost=data.get("total_cost", 0.0),
            context_window=data.get("context_window", 200000),
            parent_id=data.get("parent_id"),
            children=data.get("children", []),
            returned=data.get("returned", False),
            return_condition=data.get("return_condition", "manual"),
            working_directories=cls._load_working_directories(data),
            title=data.get("title", ""),
            summary=data.get("summary", ""),
            # Fork/merge tracking
            fork_name=data.get("fork_name", ""),
            fork_status=data.get("fork_status", "active"),
            fork_point_turn=data.get("fork_point_turn", -1),
            merge_point_turn=data.get("merge_point_turn", -1),
            merge_message=data.get("merge_message", ""),
            backend_name=data.get("backend_name", ""),
            links=data.get("links", []),
        )
        for m in data.get("messages", []):
            # Parse content_blocks if present, otherwise create from content
            raw_blocks = m.get("content_blocks", [])
            if raw_blocks:
                content_blocks = [cls._deserialize_content_block(b) for b in raw_blocks]
            else:
                # Backwards compat: create text block from content
                content_blocks = [TextBlock(text=m.get("content", ""))] if m.get("content") else []

            # Parse context_mode
            mode_str = m.get("context_mode", "copy")
            try:
                context_mode = ContextMode(mode_str)
            except ValueError:
                context_mode = ContextMode.COPY

            session.messages.append(Message(
                role=m["role"],
                content=m.get("content", ""),
                content_blocks=content_blocks,
                tokens=m.get("tokens", 0),
                timestamp=m.get("timestamp", ""),
                context_mode=context_mode,
                summary=m.get("summary", ""),
            ))
        return session

    @classmethod
    def list_sessions(cls) -> list[dict]:
        """Return list of session metadata dicts without loading full messages.

        Returns list of dicts with keys: id, created, last_modified, model, title,
        message_count, total_input_tokens, total_output_tokens, total_cost,
        parent_id, children, fork_name, fork_status.
        """
        if not SESSIONS_DIR.exists():
            return []
        sessions = []
        for path in SESSIONS_DIR.glob("*.json"):
            try:
                data = json.loads(path.read_text())
                # For backwards compat, use created if last_modified missing
                last_modified = data.get("last_modified", data.get("created", ""))
                sessions.append({
                    "id": data["id"],
                    "created": data["created"],
                    "last_modified": last_modified,
                    "model": data.get("model", ""),
                    "title": data.get("title", ""),
                    "message_count": len(data.get("messages", [])),
                    "total_input_tokens": data.get("total_input_tokens", 0),
                    "total_output_tokens": data.get("total_output_tokens", 0),
                    "total_cost": data.get("total_cost", 0.0),
                    "parent_id": data.get("parent_id"),
                    "children": data.get("children", []),
                    "fork_name": data.get("fork_name", ""),
                    "fork_status": data.get("fork_status", "active"),
                })
            except (json.JSONDecodeError, KeyError):
                continue
        return sorted(sessions, key=lambda x: x["created"], reverse=True)
