"""Core module - GUI-independent business logic for Balloons."""

from .commands import (
    Command,
    CommandParser,
    ArchiveCommand,
    RehydrateCommand,
    ReindexCommand,
    NewSessionCommand,
    CopyTurnsCommand,
    QueryWithCommand,
    SuspendCommand,
    ShellCommand,
    ForkCommand,
    MergeCommand,
    DeriveCommand,
    SwitchCommand,
    ReturnCommand,
    PwdCommand,
    CdCommand,
    ReloadCommand,
    TitleCommand,
    HelpCommand,
    BackendCommand,
    PrefsCommand,
    EditConfigCommand,
    EditPromptCommand,
    LinkCommand,
    DebugToggleCommand,
    DebugClearCommand,
    DebugPauseCommand,
    FollowCommand,
    StashCommand,
    PopCommand,
    ClearAllSessionsCommand,
    SnapCommand,
    NewSlideCommand,
    PresentCommand,
    SlidesCommand,
    ChatCommand,
    SupervisorStartCommand,
    SupervisorListCommand,
    SupervisorLogsCommand,
    SupervisorStopCommand,
    ReviewCommand,
    COMMAND_DOCS,
)
from .context import ContextBuilder
from .formatter import Formatter, format_edit_as_diff, guess_language
from .runner import SessionRunner, RunnerStatus, StreamEvent, StreamResult, HelperRunner
from .manager import SessionManager, SessionInfo
from .debug_log import debug_log, DebugLog, LogLevel, LogEntry, dump_failed_json, timed
from .base_runner import BaseRunner, RunnerEvent
from .exceptions import RateLimitError, InputRequiredError, BackendNotFoundError
from .link_tools import LINK_TOOL_NAMES, execute_link_tool, register_app_tool_handler, unregister_app_tool_handler
from .openai_runner import OpenAICompatibleRunner
from .runner_factory import create_runner, resolve_env_var, validate_backend_config, ensure_prompts_installed
from .tools import TOOLS, BALLOON_TOOLS, BALLOON_TOOL_NAMES, SUPERVISOR_TOOLS, SUPERVISOR_TOOL_NAMES, REVIEW_TOOLS, REVIEW_TOOL_NAMES, get_tools_for_request
from .tool_executor import execute_tool, parse_fork_proposal, parse_create_slide, SlideData
from .summarizer import Summarizer
from .context_grouper import (
    ContextGroups,
    group_messages_by_context_mode,
    build_context_messages,
)
from .streaming import (
    StreamingContext,
    StreamingCoordinator,
    StreamingAction,
    TextAction,
    TextFlushAction,
    InitAction,
    ResultAction,
    ToolUseStartAction,
    ToolInputDeltaAction,
    ToolUseCompleteAction,
    ToolResultAction,
    DoneAction,
    ErrorAction,
    RateLimitAction,
    CancelledAction,
    InputRequiredAction,
    HelperDoneAction,
    NoAction,
    TurnStartedAction,
    # Helper data types
    ArchiveData,
    MergeData,
    LinkData,
    ReturnData,
)
from .fork import (
    ForkManager,
    ForkResult,
    MergeResult,
    DeriveResult,
    SwitchResult,
    ForkProposal,
    ContextAssignment,
    ForkData,
    DeriveData,
)
from .command_executor import (
    CommandExecutor,
    ArchiveResult,
    RehydrateResult,
    LinkResult,
    LinkTarget,
    BackendResult,
    BackendInfo,
)
from .json_stream import StreamingJsonParser
from .stream_buffer import StreamBuffer, Timer, TimerFactory
from .task_state import (
    TaskState,
    Task,
    TaskStatus,
    TaskType,
    TaskEvent,
    SessionTaskInfo,
    AsyncObserver,
    get_task_state,
)
from .queue_state import (
    QueueState,
    QueueEvent,
    QueueSnapshot,
    QueuedMessageSnapshot,
    get_queue_state,
)
from .tts import (
    TTSRunner,
    TTSConfig,
    TTSBackend,
    get_tts_runner,
    speak,
    stop_speaking,
)
from .stash import StashedMessage, MessageStash
from .preferences import DEFAULT_TOOLS, ToolPreferences
from .async_storage import AsyncStorage, is_rust_storage_available, DEFAULT_DB_PATH
from .supervisor_tools import (
    SUPERVISOR_TOOL_NAMES as SUP_TOOL_NAMES,
    set_supervisor,
    get_supervisor,
    execute_supervisor_tool,
    get_running_count,
    stop_session_processes,
)

__all__ = [
    # Commands
    "Command",
    "CommandParser",
    "ArchiveCommand",
    "RehydrateCommand",
    "ReindexCommand",
    "NewSessionCommand",
    "CopyTurnsCommand",
    "QueryWithCommand",
    "SuspendCommand",
    "ShellCommand",
    "ForkCommand",
    "MergeCommand",
    "DeriveCommand",
    "SwitchCommand",
    "ReturnCommand",
    "PwdCommand",
    "CdCommand",
    "ReloadCommand",
    "TitleCommand",
    "HelpCommand",
    "BackendCommand",
    "PrefsCommand",
    "EditConfigCommand",
    "EditPromptCommand",
    "LinkCommand",
    "DebugToggleCommand",
    "DebugClearCommand",
    "DebugPauseCommand",
    "FollowCommand",
    "StashCommand",
    "PopCommand",
    "ClearAllSessionsCommand",
    "SnapCommand",
    "NewSlideCommand",
    "PresentCommand",
    "SlidesCommand",
    "ChatCommand",
    "SupervisorStartCommand",
    "SupervisorListCommand",
    "SupervisorLogsCommand",
    "SupervisorStopCommand",
    "ReviewCommand",
    "COMMAND_DOCS",
    # Context
    "ContextBuilder",
    # Formatting
    "Formatter",
    "format_edit_as_diff",
    "guess_language",
    # Runner
    "SessionRunner",
    "RunnerStatus",
    "StreamEvent",
    "StreamResult",
    "HelperRunner",
    # Manager
    "SessionManager",
    "SessionInfo",
    # Debug
    "debug_log",
    "DebugLog",
    "LogLevel",
    "LogEntry",
    "dump_failed_json",
    "timed",
    # Base runner
    "BaseRunner",
    "RunnerEvent",
    "OpenAICompatibleRunner",
    "create_runner",
    "resolve_env_var",
    "validate_backend_config",
    "ensure_prompts_installed",
    # Tools
    "TOOLS",
    "BALLOON_TOOLS",
    "BALLOON_TOOL_NAMES",
    "SUPERVISOR_TOOLS",
    "SUPERVISOR_TOOL_NAMES",
    "REVIEW_TOOLS",
    "REVIEW_TOOL_NAMES",
    "LINK_TOOL_NAMES",
    "get_tools_for_request",
    "execute_tool",
    "parse_fork_proposal",
    "parse_create_slide",
    "SlideData",
    "register_app_tool_handler",
    "unregister_app_tool_handler",
    # Supervisor tools
    "set_supervisor",
    "get_supervisor",
    "execute_supervisor_tool",
    "get_running_count",
    "stop_session_processes",
    # Summarizer
    "Summarizer",
    # Context grouper
    "ContextGroups",
    "group_messages_by_context_mode",
    "build_context_messages",
    # Streaming
    "StreamingContext",
    "StreamingCoordinator",
    "StreamingAction",
    "TextAction",
    "TextFlushAction",
    "InitAction",
    "ResultAction",
    "ToolUseStartAction",
    "ToolInputDeltaAction",
    "ToolUseCompleteAction",
    "ToolResultAction",
    "DoneAction",
    "ErrorAction",
    "RateLimitAction",
    "CancelledAction",
    "InputRequiredAction",
    "HelperDoneAction",
    "NoAction",
    "TurnStartedAction",
    # Helper data types
    "ArchiveData",
    "MergeData",
    "LinkData",
    "ReturnData",
    # Fork operations
    "ForkManager",
    "ForkResult",
    "MergeResult",
    "DeriveResult",
    "SwitchResult",
    "ForkProposal",
    "ContextAssignment",
    "ForkData",
    "DeriveData",
    # Command executor
    "CommandExecutor",
    "ArchiveResult",
    "RehydrateResult",
    "LinkResult",
    "LinkTarget",
    "BackendResult",
    "BackendInfo",
    # JSON streaming
    "StreamingJsonParser",
    # Exceptions
    "RateLimitError",
    "InputRequiredError",
    "BackendNotFoundError",
    # Link tools
    "execute_link_tool",
    # Stream buffer
    "StreamBuffer",
    "Timer",
    "TimerFactory",
    # Task state
    "TaskState",
    "Task",
    "TaskStatus",
    "TaskType",
    "TaskEvent",
    "SessionTaskInfo",
    "AsyncObserver",
    "get_task_state",
    # Queue state
    "QueueState",
    "QueueEvent",
    "QueueSnapshot",
    "QueuedMessageSnapshot",
    "get_queue_state",
    # TTS
    "TTSRunner",
    "TTSConfig",
    "TTSBackend",
    "get_tts_runner",
    "speak",
    "stop_speaking",
    # Stash
    "StashedMessage",
    "MessageStash",
    # Preferences
    "DEFAULT_TOOLS",
    "ToolPreferences",
    # Storage
    "AsyncStorage",
    "is_rust_storage_available",
    "DEFAULT_DB_PATH",
]
