[package]
name = "balloons-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
core-executor.workspace = true
redb.workspace = true
serde.workspace = true
serde_json.workspace = true
async-trait.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
futures-lite.workspace = true
